In [13]:
from IPython.display import display
import pandas as pd

from src import config

In [2]:
data_dir = config.dir_data / "icecat-taxonomy"

In [3]:
taxonomy_cases = pd.read_excel(data_dir + "mobile_phone_cases.xlsx")
taxonomy_cases

,Catid,UNSPSC,Global feature group ID,Feature group,Feature_id,Feature,Is mandatory,Is searchable,Type,Restricted values,Measure sign
0,2779,43191691,14,Weight & dimensions,1649,Width,0,0,numerical,NaN,mm
1,2779,43191691,14,Weight & dimensions,1650,Depth,0,0,numerical,NaN,mm
2,2779,43191691,14,Weight & dimensions,1464,Height,0,0,numerical,NaN,mm
3,2779,43191691,14,Weight & dimensions,94,Weight,0,0,numerical,NaN,g
4,2779,43191691,14,Weight & dimensions,2646,Interior dimensions (W x D x H),0,0,3d,NaN,mm
...,...,...,...,...,...,...,...,...,...,...,...
63,2779,43191691,185,Features,1766,Product colour,1,1,multi_dropdown,Aluminium\nAnthracite\nAssorted colours\nBeige...,NaN
64,2779,43191691,185,Features,898,Material,1,1,multi_dropdown,Aramide\nABS synthetics\nABS\nAcrylic\nEgg she...,NaN
65,2779,43191691,185,Features,8156,Brand compatibility,1,1,dropdown,Apple\nSamsung\nSony\nHTC\nLG\nUniversal\nNoki...,NaN
66,2779,43191691,185,Features,6767,Maximum screen size,1,1,numerical,NaN,""""
67,2779,43191691,185,Features,8778,Case type,1,1,dropdown,Armband case\nCover case\nFlip case\nFolio cas...,NaN

In [4]:
taxonomy_phones = pd.read_excel(data_dir + "smartphones.xlsx")
taxonomy_phones

,Catid,UNSPSC,Global feature group ID,Feature group,Feature_id,Feature,Is mandatory,Is searchable,Type,Restricted values,Measure sign
0,1893,43191528,14,Weight & dimensions,1649,Width,0,0,numerical,NaN,mm
1,1893,43191528,14,Weight & dimensions,1650,Depth,0,0,numerical,NaN,mm
2,1893,43191528,14,Weight & dimensions,1464,Height,0,0,numerical,NaN,mm
3,1893,43191528,47,Storage,730,Compatible memory cards,1,0,multi_dropdown,CF\nCF+\nCF Type II\nexpressP2\nMemory Stick (...,NaN
4,1893,43191528,47,Storage,7021,Maximum memory card size,0,0,numerical,NaN,GB
...,...,...,...,...,...,...,...,...,...,...,...
349,1893,43191528,54,Navigation,26425,Position location,1,1,y_n,NaN,NaN
350,1893,43191528,95,Camera,27587,Rear camera type,1,1,dropdown,Single camera\nDual camera\nTriple camera\nQua...,NaN
351,1893,43191528,47,Storage,7861,RAM capacity,1,1,numerical,NaN,GB
352,1893,43191528,90,Software,75,Platform,1,1,dropdown,Android\nAsha\nBada\nBlackBerry\nFirefox\niOS\...,NaN
353,1893,43191528,35,Network,40629,Mobile network generation,1,1,dropdown,2G\n3G\n4G\n5G,NaN

In [5]:
ids_cases = set(taxonomy_cases["Feature_id"])
ids_phones = set(taxonomy_phones["Feature_id"])

ids = ids_cases.union(ids_phones)
ids_both = ids_cases.intersection(ids_phones)

print("unique ids:", len(ids))
print("shared ids:", len(ids_both))

unique ids: 390
shared ids: 32

In [6]:
features_cases = taxonomy_cases[["Feature_id", "Feature", "Feature group", "Type", "Is mandatory"]]

column_name = {
    "Feature_id": "id",
    "Feature": "name_cases",
    "Feature group": "group_cases",
    "Type": "type_cases",
    "Is mandatory": "required_cases",
}

features_cases = features_cases.rename(columns=column_name)
features_cases

,id,name_cases,group_cases,type_cases,required_cases
0,1649,Width,Weight & dimensions,numerical,0
1,1650,Depth,Weight & dimensions,numerical,0
2,1464,Height,Weight & dimensions,numerical,0
3,94,Weight,Weight & dimensions,numerical,0
4,2646,Interior dimensions (W x D x H),Weight & dimensions,3d,0
...,...,...,...,...,...
63,1766,Product colour,Features,multi_dropdown,1
64,898,Material,Features,multi_dropdown,1
65,8156,Brand compatibility,Features,dropdown,1
66,6767,Maximum screen size,Features,numerical,1
67,8778,Case type,Features,dropdown,1

In [7]:
features_phones = taxonomy_phones[["Feature_id", "Feature", "Feature group", "Type", "Is mandatory"]]

column_name = {
    "Feature_id": "id",
    "Feature": "name_phones",
    "Feature group": "group_phones",
    "Type": "type_phones",
    "Is mandatory": "required_phones",
}

features_phones = features_phones.rename(columns=column_name)
features_phones

,id,name_phones,group_phones,type_phones,required_phones
0,1649,Width,Weight & dimensions,numerical,0
1,1650,Depth,Weight & dimensions,numerical,0
2,1464,Height,Weight & dimensions,numerical,0
3,730,Compatible memory cards,Storage,multi_dropdown,1
4,7021,Maximum memory card size,Storage,numerical,0
...,...,...,...,...,...
349,26425,Position location,Navigation,y_n,1
350,27587,Rear camera type,Camera,dropdown,1
351,7861,RAM capacity,Storage,numerical,1
352,75,Platform,Software,dropdown,1
353,40629,Mobile network generation,Network,dropdown,1

In [8]:
features = pd.merge(features_cases, features_phones, 'outer')
features

,id,name_cases,group_cases,type_cases,required_cases,name_phones,group_phones,type_phones,required_phones
0,1649,Width,Weight & dimensions,numerical,0.0,Width,Weight & dimensions,numerical,0.0
1,1650,Depth,Weight & dimensions,numerical,0.0,Depth,Weight & dimensions,numerical,0.0
2,1464,Height,Weight & dimensions,numerical,0.0,Height,Weight & dimensions,numerical,0.0
3,94,Weight,Weight & dimensions,numerical,0.0,Weight,Weight & dimensions,numerical,1.0
4,2646,Interior dimensions (W x D x H),Weight & dimensions,3d,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
385,26425,NaN,NaN,NaN,NaN,Position location,Navigation,y_n,1.0
386,27587,NaN,NaN,NaN,NaN,Rear camera type,Camera,dropdown,1.0
387,7861,NaN,NaN,NaN,NaN,RAM capacity,Storage,numerical,1.0
388,75,NaN,NaN,NaN,NaN,Platform,Software,dropdown,1.0
389,40629,NaN,NaN,NaN,NaN,Mobile network generation,Network,dropdown,1.0

In [14]:
for field_name in ["name", "group", "type"]:
    key_cases = f"{field_name}_cases"
    key_phones = f"{field_name}_phones"

    tmp = features[
        features[key_cases].notna() & features[key_phones].notna() &
        (features[key_cases] != features[key_phones])
    ]
    print(f"--- {field_name} -------------------")
    display(tmp[["id", key_cases, key_phones]])

--- name -------------------

Empty DataFrame
Columns: [id, name_cases, name_phones]
Index: []

--- group -------------------

       id     group_cases         group_phones
6    8801  Packaging data    Packaging content
7    3808  Packaging data  Weight & dimensions
8    3806  Packaging data  Weight & dimensions
9    3807  Packaging data  Weight & dimensions
10    762  Packaging data  Weight & dimensions
12   8072        Features               Design
14    909        Features              Battery
18   3294        Features          Performance
30   7900        Features               Design
33  12148        Features          Performance
36  17956        Features               Design
53  14752        Features              Display
63   1766        Features               Design

--- type -------------------

      id type_cases     type_phones
12  8072   dropdown  multi_dropdown

In [17]:
tmp = features[
    features["group_cases"].notna() & features["group_phones"].notna() &
    (features["group_cases"] != features["group_phones"])
]

tmp[["id", "name_cases", "group_cases", "group_phones"]]

,id,name_cases,group_cases,group_phones
6,8801,Screen protector,Packaging data,Packaging content
7,3808,Package width,Packaging data,Weight & dimensions
8,3806,Package depth,Packaging data,Weight & dimensions
9,3807,Package height,Packaging data,Weight & dimensions
10,762,Package weight,Packaging data,Weight & dimensions
12,8072,Protection features,Features,Design
14,909,Battery capacity,Features,Battery
18,3294,Country of origin,Features,Performance
30,7900,International Protection (IP) code,Features,Design
33,12148,Wireless charging,Features,Performance
36,17956,Colour name,Features,Design
53,14752,Fingerprint resistant,Features,Display
63,1766,Product colour,Features,Design

In [19]:
taxonomy_cases[taxonomy_cases["Feature group"] == "Packaging data"]

,Catid,UNSPSC,Global feature group ID,Feature group,Feature_id,Feature,Is mandatory,Is searchable,Type,Restricted values,Measure sign
6,2779,43191691,67,Packaging data,8801,Screen protector,0,0,y_n,NaN,NaN
7,2779,43191691,67,Packaging data,3808,Package width,0,0,numerical,NaN,mm
8,2779,43191691,67,Packaging data,3806,Package depth,0,0,numerical,NaN,mm
9,2779,43191691,67,Packaging data,3807,Package height,0,0,numerical,NaN,mm
10,2779,43191691,67,Packaging data,762,Package weight,0,0,numerical,NaN,g
19,2779,43191691,67,Packaging data,4463,Package type,0,0,dropdown,Box\nBlister\nHanging box\nWindow box\nOpen bo...,NaN
35,2779,43191691,67,Packaging data,20228,Quantity per pack,0,0,numerical,NaN,pc(s)
61,2779,43191691,67,Packaging data,12935,Lanyard,0,0,y_n,NaN,NaN

In [23]:
columns = ["Feature_id", "Feature", "Feature group", "Type", "Is mandatory"]
column_names = {
    "Feature_id": "id",
    "Feature": "name",
    "Feature group": "group",
    "Type": "type",
    "Is mandatory": "required_cases",
}

features_cases = taxonomy_cases[columns]
features_cases = features_cases.rename(columns=column_names)

column_names["Is mandatory"] = "required_phones"

features_phones = taxonomy_phones[columns]
features_phones = features_phones.rename(columns=column_names)

features = pd.merge(features_cases, features_phones, "outer")
features

,id,name,group,type,required_cases,required_phones
0,1649,Width,Weight & dimensions,numerical,0.0,0.0
1,1650,Depth,Weight & dimensions,numerical,0.0,0.0
2,1464,Height,Weight & dimensions,numerical,0.0,0.0
3,94,Weight,Weight & dimensions,numerical,0.0,1.0
4,2646,Interior dimensions (W x D x H),Weight & dimensions,3d,0.0,NaN
...,...,...,...,...,...,...
398,26425,Position location,Navigation,y_n,NaN,1.0
399,27587,Rear camera type,Camera,dropdown,NaN,1.0
400,7861,RAM capacity,Storage,numerical,NaN,1.0
401,75,Platform,Software,dropdown,NaN,1.0
402,40629,Mobile network generation,Network,dropdown,NaN,1.0

In [30]:
features[features.duplicated("id", keep="first") | features.duplicated("id", keep="last")].sort_values("id")

,id,name,group,type,required_cases,required_phones
255,762,Package weight,Weight & dimensions,numerical,NaN,0.0
10,762,Package weight,Packaging data,numerical,0.0,NaN
392,909,Battery capacity,Battery,numerical,NaN,1.0
14,909,Battery capacity,Features,numerical,0.0,NaN
63,1766,Product colour,Features,multi_dropdown,1.0,NaN
397,1766,Product colour,Design,multi_dropdown,NaN,1.0
18,3294,Country of origin,Features,dropdown,0.0,NaN
251,3294,Country of origin,Performance,dropdown,NaN,0.0
253,3806,Package depth,Weight & dimensions,numerical,NaN,0.0
8,3806,Package depth,Packaging data,numerical,0.0,NaN
9,3807,Package height,Packaging data,numerical,0.0,NaN
254,3807,Package height,Weight & dimensions,numerical,NaN,0.0
7,3808,Package width,Packaging data,numerical,0.0,NaN
252,3808,Package width,Weight & dimensions,numerical,NaN,0.0
30,7900,International Protection (IP) code,Features,dropdown,0.0,NaN
161,7900,International Protection (IP) code,Design,dropdown,NaN,0.0
149,8072,Protection features,Design,multi_dropdown,NaN,0.0
12,8072,Protection features,Features,dropdown,0.0,NaN
6,8801,Screen protector,Packaging data,y_n,0.0,NaN
156,8801,Screen protector,Packaging content,y_n,NaN,0.0
33,12148,Wireless charging,Features,y_n,0.0,NaN
159,12148,Wireless charging,Performance,y_n,NaN,0.0
53,14752,Fingerprint resistant,Features,y_n,0.0,NaN
240,14752,Fingerprint resistant,Display,y_n,NaN,0.0
36,17956,Colour name,Features,text,0.0,NaN
275,17956,Colour name,Design,text,NaN,0.0