In [1]:
import shutil

from IPython.display import display
import pandas as pd

from akeneo import create_from_env
from config import data_dir

In [2]:
connector, client = create_from_env("ecommerce", "en_US")

In [3]:
funcs = [
    connector.get_categories,
    connector.get_families,
]

for func in funcs:
    df = pd.DataFrame(func())
    display(df)

                     code          parent              labels
0                  master            None      Master catalog
1          tvs_projectors          master  TVs and projectors
2             pc_monitors  tvs_projectors         PC Monitors
3                 led_tvs  tvs_projectors             LED TVs
4                 cameras          master             Cameras
..                    ...             ...                 ...
163             suppliers            None           Suppliers
164        supplier_mongo       suppliers               Mongo
165         supplier_zaro       suppliers                Zaro
166  supplier_the_tootles       suppliers         The Tootles
167       supplier_abibas       suppliers              Abibas

[168 rows x 3 columns]

,code,attributes,labels
0,accessories,"[brand, collection, color, composition, descri...",Accessories
1,camcorders,"[description, image_stabilizer, name, optical_...",Camcorders
2,clothing,"[brand, care_instructions, collection, color, ...",Clothing
3,digital_cameras,"[auto_exposure, auto_focus_assist_beam, auto_f...",Digital cameras
4,headphones,"[description, headphone_connectivity, name, pi...",Headphones
5,laser_led_printers,"[description, maximum_print_size, name, pictur...",Laser and LED printers
6,led_tvs,"[description, display_diagonal, name, picture,...",LED TVs
7,loudspeakers,"[description, name, picture, power_requirement...",Loudspeakers
8,mp3_players,"[description, name, picture, power_requirement...",MP3 players
9,mugs,"[container_material, description, main_color, ...",Mugs
10,multifunctionals,"[color_scanning, description, maximum_print_si...",Multifunctionals
11,pc_monitors,"[description, display_color, display_diagonal,...",PC Monitors
12,scanners,"[color_scanning, description, maximum_scan_siz...",Scanners
13,shoes,"[brand, collection, color, composition, descri...",Shoes
14,tablets,"[description, name, picture, power_requirement...",Tablets
15,tshirts,"[clothing_size, description, main_color, name,...",T-shirts
16,webcams,"[description, maximum_frame_rate, maximum_vide...",Webcams

In [4]:
res = client.get_list("pim_api_attribute_list")
df = pd.DataFrame(res)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   code                    77 non-null     object
 1   type                    77 non-null     object
 2   group                   77 non-null     object
 3   unique                  77 non-null     bool
 4   useable_as_grid_filter  77 non-null     bool
 5   allowed_extensions      77 non-null     object
 6   metric_family           4 non-null      object
 7   default_metric_unit     4 non-null      object
 8   reference_data_name     0 non-null      object
 9   available_locales       77 non-null     object
 10  max_characters          0 non-null      object
 11  validation_rule         0 non-null      object
 12  validation_regexp       0 non-null      object
 13  wysiwyg_enabled         1 non-null      object
 14  number_min              0 non-null      object
 15  number_max              0 non-null      object
 16  decimals_allowed        13 non-null     object
 17  negative_allowed        12 non-null     object
 18  date_min                0 non-null      object
 19  date_max                0 non-null      object
 20  max_file_size           0 non-null      object
 21  minimum_input_length    0 non-null      object
 22  sort_order              77 non-null     int64
 23  localizable             77 non-null     bool
 24  scopable                77 non-null     bool
 25  labels                  77 non-null     object
 26  auto_option_sorting     1 non-null      object
 27  default_value           0 non-null      object
 28  group_labels            77 non-null     object
dtypes: bool(4), int64(1), object(24)
memory usage: 15.5+ KB

In [5]:
res = connector.get_attributes()
df = pd.DataFrame(res)
df

,code,type,labels,localizable,scopable,unique,group,group_labels,sort_order,allowed_extensions,...,max_file_size,metric_family,minimum_input_length,negative_allowed,number_min,number_max,reference_data_name,validation_rule,validation_regexp,wysiwyg_enabled
0,auto_exposure,AkeneoAttributeType.BOOL,Auto exposure,False,False,False,technical,Technical,39,[],...,None,None,None,None,None,None,None,None,None,None
1,auto_focus_assist_beam,AkeneoAttributeType.BOOL,Auto focus beam,False,False,False,technical,Technical,34,[],...,None,None,None,None,None,None,None,None,None,None
2,auto_focus_lock,AkeneoAttributeType.BOOL,Auto focus lock,False,False,False,technical,Technical,33,[],...,None,None,None,None,None,None,None,None,None,None
3,auto_focus_modes,AkeneoAttributeType.TEXT,Auto focus modes,True,False,False,technical,Technical,31,[],...,None,None,None,None,None,None,None,None,None,None
4,auto_focus_points,AkeneoAttributeType.NUMBER,Auto focus points,False,False,False,technical,Technical,32,[],...,None,None,None,False,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,variation_image,AkeneoAttributeType.IMAGE,Variant picture,False,False,False,medias,Media,20,"[png, jpeg, jpg]",...,None,None,None,None,None,None,None,None,None,None
73,variation_name,AkeneoAttributeType.TEXT,Variant Name,True,False,False,marketing,Marketing,4,[],...,None,None,None,None,None,None,None,None,None,None
74,viewing_area,AkeneoAttributeType.METRIC,Effective viewing area,False,False,False,technical,Technical,20,[],...,None,Length,None,False,None,None,None,None,None,None
75,wash_temperature,AkeneoAttributeType.SELECT_SINGLE,Wash temperature,False,False,False,product,Product,6,[],...,None,None,None,None,None,None,None,None,None,None
76,weight,AkeneoAttributeType.METRIC,Weight,False,False,False,technical,Technical,1,[],...,None,Weight,None,False,None,None,None,None,None,None

In [8]:
csv_dir = data_dir / "02-akeneo-data-cleaned"
shutil.rmtree(csv_dir, ignore_errors=True)
csv_dir.mkdir(parents=True, exist_ok=True)

cases = [
    ("attributes", connector.get_attributes),
    ("categories", connector.get_categories),
    ("families", connector.get_families),
    ("products", connector.get_products),
]

for name, func in cases:
    res = func()
    df = pd.DataFrame(res)
    print(f"--- {name} -----------------------------")
    display(df)
    df.to_csv(csv_dir / f"{name}.csv", index=False)

    if name == "products":
        res = [prod.values for prod in res]
        df = pd.DataFrame(res)
        print(f"--- {name}__values -----------------------------")
        display(df)
        df.to_csv(csv_dir / f"{name}__values.csv", index=False)

--- attributes -----------------------------

,code,type,labels,localizable,scopable,unique,group,group_labels,sort_order,allowed_extensions,...,max_file_size,metric_family,minimum_input_length,negative_allowed,number_min,number_max,reference_data_name,validation_rule,validation_regexp,wysiwyg_enabled
0,auto_exposure,AkeneoAttributeType.BOOL,Auto exposure,False,False,False,technical,Technical,39,[],...,None,None,None,None,None,None,None,None,None,None
1,auto_focus_assist_beam,AkeneoAttributeType.BOOL,Auto focus beam,False,False,False,technical,Technical,34,[],...,None,None,None,None,None,None,None,None,None,None
2,auto_focus_lock,AkeneoAttributeType.BOOL,Auto focus lock,False,False,False,technical,Technical,33,[],...,None,None,None,None,None,None,None,None,None,None
3,auto_focus_modes,AkeneoAttributeType.TEXT,Auto focus modes,True,False,False,technical,Technical,31,[],...,None,None,None,None,None,None,None,None,None,None
4,auto_focus_points,AkeneoAttributeType.NUMBER,Auto focus points,False,False,False,technical,Technical,32,[],...,None,None,None,False,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,variation_image,AkeneoAttributeType.IMAGE,Variant picture,False,False,False,medias,Media,20,"[png, jpeg, jpg]",...,None,None,None,None,None,None,None,None,None,None
73,variation_name,AkeneoAttributeType.TEXT,Variant Name,True,False,False,marketing,Marketing,4,[],...,None,None,None,None,None,None,None,None,None,None
74,viewing_area,AkeneoAttributeType.METRIC,Effective viewing area,False,False,False,technical,Technical,20,[],...,None,Length,None,False,None,None,None,None,None,None
75,wash_temperature,AkeneoAttributeType.SELECT_SINGLE,Wash temperature,False,False,False,product,Product,6,[],...,None,None,None,None,None,None,None,None,None,None
76,weight,AkeneoAttributeType.METRIC,Weight,False,False,False,technical,Technical,1,[],...,None,Weight,None,False,None,None,None,None,None,None

--- categories -----------------------------

                     code          parent              labels
0                  master            None      Master catalog
1          tvs_projectors          master  TVs and projectors
2             pc_monitors  tvs_projectors         PC Monitors
3                 led_tvs  tvs_projectors             LED TVs
4                 cameras          master             Cameras
..                    ...             ...                 ...
163             suppliers            None           Suppliers
164        supplier_mongo       suppliers               Mongo
165         supplier_zaro       suppliers                Zaro
166  supplier_the_tootles       suppliers         The Tootles
167       supplier_abibas       suppliers              Abibas

[168 rows x 3 columns]

--- families -----------------------------

,code,attributes,labels
0,accessories,"[brand, collection, color, composition, descri...",Accessories
1,camcorders,"[description, image_stabilizer, name, optical_...",Camcorders
2,clothing,"[brand, care_instructions, collection, color, ...",Clothing
3,digital_cameras,"[auto_exposure, auto_focus_assist_beam, auto_f...",Digital cameras
4,headphones,"[description, headphone_connectivity, name, pi...",Headphones
5,laser_led_printers,"[description, maximum_print_size, name, pictur...",Laser and LED printers
6,led_tvs,"[description, display_diagonal, name, picture,...",LED TVs
7,loudspeakers,"[description, name, picture, power_requirement...",Loudspeakers
8,mp3_players,"[description, name, picture, power_requirement...",MP3 players
9,mugs,"[container_material, description, main_color, ...",Mugs
10,multifunctionals,"[color_scanning, description, maximum_print_si...",Multifunctionals
11,pc_monitors,"[description, display_color, display_diagonal,...",PC Monitors
12,scanners,"[color_scanning, description, maximum_scan_siz...",Scanners
13,shoes,"[brand, collection, color, composition, descri...",Shoes
14,tablets,"[description, name, picture, power_requirement...",Tablets
15,tshirts,"[clothing_size, description, main_color, name,...",T-shirts
16,webcams,"[description, maximum_frame_rate, maximum_vide...",Webcams

--- products -----------------------------

,identifier,enabled,family,categories,groups,parent,values,created,updated,associations,quantified_associations
0,1111111171,True,accessories,"[master_accessories_bags, print_accessories, s...",[],None,{'image': 'f/e/9/6/fe960148cdaa746093eb734cd82...,2022-01-12 12:08:58+00:00,2022-01-12 12:08:59+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
1,13620748,True,led_tvs,"[led_tvs, samsung, tvs_projectors_sales]",[],None,"{'name': 'Samsung UE40ES5500PXZT LED TV', 'dis...",2022-01-12 12:08:58+00:00,2022-01-12 12:08:59+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
2,15554974,True,webcams,"[cameras_sales, logitech, webcams]",[],None,"{'maximum_video_resolution': '640_x_480', 'nam...",2022-01-12 12:08:58+00:00,2022-01-12 12:08:59+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
3,12249740,True,scanners,"[avision, print_scan_sales, scanners]",[],None,{'picture': 'c/2/d/f/c2df1e701322f576b6e477653...,2022-01-12 12:09:22+00:00,2022-01-12 12:09:22+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
4,1111111130,True,clothing,"[master_men_blazers_deals, supplier_zaro]",[],apollon_yellow,"{'size': 'xs', 'color': 'yellow', 'supplier': ...",2022-01-12 12:09:24+00:00,2022-01-12 12:09:24+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
...,...,...,...,...,...,...,...,...,...,...,...
1234,1111111125,True,clothing,"[master_men_blazers_deals, supplier_zaro]",[],apollon_pink,"{'size': 'xs', 'color': 'pink', 'supplier': 'z...",2022-01-12 12:09:22+00:00,2022-01-12 12:09:22+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
1235,1111111126,True,clothing,"[master_men_blazers_deals, supplier_zaro]",[],apollon_red,"{'size': 'xxl', 'color': 'red', 'supplier': 'z...",2022-01-12 12:09:22+00:00,2022-01-12 12:09:22+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
1236,1111111127,True,clothing,"[master_men_blazers_deals, supplier_zaro]",[],apollon_red,"{'size': 'm', 'color': 'red', 'supplier': 'zar...",2022-01-12 12:09:22+00:00,2022-01-12 12:09:22+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
1237,1111111128,True,clothing,"[master_men_blazers_deals, supplier_zaro]",[],apollon_yellow,"{'size': 'm', 'color': 'yellow', 'supplier': '...",2022-01-12 12:09:22+00:00,2022-01-12 12:09:22+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
1238,1111111129,True,clothing,"[master_men_blazers_deals, supplier_zaro]",[],apollon_yellow,"{'size': 's', 'color': 'yellow', 'supplier': '...",2022-01-12 12:09:22+00:00,2022-01-12 12:09:22+00:00,"{'PACK': {'products': [], 'product_models': []...",{}

--- products__values -----------------------------

,image,ean,name,weight,display_diagonal,description,release_date,maximum_video_resolution,total_megapixels,picture,...,power_requirements,eu_shoes_size,maximum_frame_rate,image_stabilizer,brand,material,meta_title,composition,care_instructions,main_color
0,f/e/9/6/fe960148cdaa746093eb734cd82a36ffe9b6ff...,1234567890183,Bag,500.0000,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Samsung UE40ES5500PXZT LED TV,NaN,40.0,"Samsung UE40ES5500PXZT. HD type: Full HD, Disp...",2012-03-29 00:00:00+00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Logitech C170,NaN,NaN,<b>The easy way to start video calling and sen...,2012-09-13 00:00:00+00:00,640_x_480,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Avision AV36,NaN,NaN,<b>Mobile power by USB</b>\nDonâ€™t just haul th...,2012-01-05 00:00:00+00:00,NaN,NaN,c/2/d/f/c2df1e701322f576b6e477653e8db7ebe78ea2...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8/4/f/9/84f9f9f4a41331b349c54d2a67373fa1b7df1d...,1234567890142,Long gray suit jacket and matching pants unstr...,600.0000,NaN,Long gray suit jacket and matching pants unstr...,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,8/4/f/9/84f9f9f4a41331b349c54d2a67373fa1b7df1d...,1234567890137,Long gray suit jacket and matching pants unstr...,600.0000,NaN,Long gray suit jacket and matching pants unstr...,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1235,8/4/f/9/84f9f9f4a41331b349c54d2a67373fa1b7df1d...,1234567890138,Long gray suit jacket and matching pants unstr...,900.0000,NaN,Long gray suit jacket and matching pants unstr...,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1236,8/4/f/9/84f9f9f4a41331b349c54d2a67373fa1b7df1d...,1234567890139,Long gray suit jacket and matching pants unstr...,800.0000,NaN,Long gray suit jacket and matching pants unstr...,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1237,8/4/f/9/84f9f9f4a41331b349c54d2a67373fa1b7df1d...,1234567890140,Long gray suit jacket and matching pants unstr...,800.0000,NaN,Long gray suit jacket and matching pants unstr...,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1238,8/4/f/9/84f9f9f4a41331b349c54d2a67373fa1b7df1d...,1234567890141,Long gray suit jacket and matching pants unstr...,800.0000,NaN,Long gray suit jacket and matching pants unstr...,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN