In [1]:

import os

from IPython.display import display
import pandas as pd

from akeneo import AkeneoClient, AkeneoConnector, create_client_from_env
from config import data_dir

In [3]:
csv_dir = data_dir / "0-exploration"
try:
    os.mkdir(csv_dir)
except:
    pass

In [4]:
client: AkeneoClient = create_client_from_env()
connector = AkeneoConnector(client, "en_US")

In [10]:
lists = [
    ("attributes", connector.get_attributes),
    ("categories", connector.get_categories),
    ("families", connector.get_families),
    ("product-models", connector.get_product_models),
    ("products", connector.get_products),
]

for name, getter in lists:
    values = getter()
    df = pd.DataFrame(values)
    df.to_csv(csv_dir / f"{name}.csv", index=False)
    display(f"--- {name} ---------------------------")
    display(df.head())

'--- attributes ---------------------------'

,code,type,group,unique,useable_as_grid_filter,allowed_extensions,metric_family,default_metric_unit,reference_data_name,available_locales,...,date_max,max_file_size,minimum_input_length,sort_order,localizable,scopable,labels,auto_option_sorting,default_value,group_labels
0,auto_exposure,pim_catalog_boolean,technical,False,True,[],None,None,None,[],...,None,None,None,39,False,False,Auto exposure,None,None,Technical
1,auto_focus_assist_beam,pim_catalog_boolean,technical,False,True,[],None,None,None,[],...,None,None,None,34,False,False,Auto focus beam,None,None,Technical
2,auto_focus_lock,pim_catalog_boolean,technical,False,True,[],None,None,None,[],...,None,None,None,33,False,False,Auto focus lock,None,None,Technical
3,auto_focus_modes,pim_catalog_text,technical,False,True,[],None,None,None,[],...,None,None,None,31,True,False,Auto focus modes,None,None,Technical
4,auto_focus_points,pim_catalog_number,technical,False,True,[],None,None,None,[],...,None,None,None,32,False,False,Auto focus points,None,None,Technical

'--- categories ---------------------------'

             code          parent              labels
0          master            None      Master catalog
1  tvs_projectors          master  TVs and projectors
2     pc_monitors  tvs_projectors         PC Monitors
3         led_tvs  tvs_projectors             LED TVs
4         cameras          master             Cameras

'--- families ---------------------------'

,code,attributes,labels
0,accessories,"[brand, collection, color, composition, descri...",Accessories
1,camcorders,"[description, image_stabilizer, name, optical_...",Camcorders
2,clothing,"[brand, care_instructions, collection, color, ...",Clothing
3,digital_cameras,"[auto_exposure, auto_focus_assist_beam, auto_f...",Digital cameras
4,headphones,"[description, headphone_connectivity, name, pi...",Headphones

'--- product-models ---------------------------'

,code,family,family_variant,parent,categories,values,created,updated,associations,quantified_associations
0,amor,clothing,clothing_colorsize,None,"[master_men_blazers, supplier_zaro]","{'supplier': [{'locale': None, 'scope': None, ...",2022-01-04T20:55:34+00:00,2022-01-04T20:55:34+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
1,brooksblue,shoes,shoes_size,None,[master_men_shoes],"{'color': [{'locale': None, 'scope': None, 'da...",2022-01-04T20:55:34+00:00,2022-01-04T20:55:34+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
2,brookspink,shoes,shoes_size,None,[master_women_shoes],"{'color': [{'locale': None, 'scope': None, 'da...",2022-01-04T20:55:34+00:00,2022-01-04T20:55:34+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
3,caelus,clothing,clothing_color_size,None,"[master_men_blazers_deals, supplier_mongo]","{'supplier': [{'locale': None, 'scope': None, ...",2022-01-04T20:55:34+00:00,2022-01-04T20:55:34+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
4,climbingshoe,shoes,shoes_size,None,"[master_men_shoes, print_shoes, supplier_abibas]","{'supplier': [{'locale': None, 'scope': None, ...",2022-01-04T20:55:34+00:00,2022-01-04T20:55:34+00:00,"{'PACK': {'products': [], 'product_models': []...",{}

'--- products ---------------------------'

,identifier,enabled,family,categories,groups,parent,values,created,updated,associations,quantified_associations
0,1111111171,True,accessories,"[master_accessories_bags, print_accessories, s...",[],None,"{'image': [{'locale': None, 'scope': None, 'da...",2022-01-04T20:55:42+00:00,2022-01-04T20:55:42+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
1,13620748,True,led_tvs,"[led_tvs, samsung, tvs_projectors_sales]",[],None,"{'name': [{'locale': None, 'scope': None, 'dat...",2022-01-04T20:55:42+00:00,2022-01-04T20:55:42+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
2,15554974,True,webcams,"[cameras_sales, logitech, webcams]",[],None,"{'maximum_video_resolution': [{'locale': None,...",2022-01-04T20:55:42+00:00,2022-01-04T20:55:42+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
3,12249740,True,scanners,"[avision, print_scan_sales, scanners]",[],None,"{'picture': [{'locale': None, 'scope': None, '...",2022-01-04T20:56:08+00:00,2022-01-04T20:56:08+00:00,"{'PACK': {'products': [], 'product_models': []...",{}
4,1111111130,True,clothing,"[master_men_blazers_deals, supplier_zaro]",[],apollon_yellow,"{'size': [{'locale': None, 'scope': None, 'dat...",2022-01-04T20:56:11+00:00,2022-01-04T20:56:11+00:00,"{'PACK': {'products': [], 'product_models': []...",{}